module.exports = ["Acushnet Company",
    "Adams Golf",
    "Ben Hogan Golf",
    "Bettinardi Golf",
    'Callaway Golf Company',
    'Cleveland Golf',
    'Club Car',
    'Cobra Golf',
    'Dunlop Sport',
    'Element 21',
    'Galvin Green',
    'Glenmuir',
    'John Letters',
    'Lamkin Grips',
    'Loudmouth Golf',
    'MacGregor Golf',
    'Maxfli',
    'Mizuno',
    'Nike Golf',
    'Odyssey Golf',
    'Penfold Golf',
    'PING',
    'PXG',
    'Scotty Cameron',
    'Slazenger',
    'Srixon',
    'STX',
    'TaylorMade',
    'Titleist', 
    'Vokey Design', 
    'Wilson Staff',
    'Yonex']